options:
  merge-default-rules: false
files:
  include: 'app/styles/*.s+(a|c)ss'
rules:
  no-important: 1
  no-color-literals: 2
  variable-for-property:
    - 2
    -
      properties:
      - 'border-radius'
      - 'border-top-left-radius'
      - 'border-top-right-radius'
      - 'border-bottom-left-radius'
      - 'border-bottom-right-radius'
      - 'font-family'
      - 'font-size'
      - 'z-index'
