apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: tomwilkie/app
        imagePullPolicy: IfNotPresent
        args:
          - -echo=http://echo.default.svc.cluster.local/
          - -qotd=qotd.default.svc.cluster.local
          - -redis=redis.default.svc.cluster.local
          - -search=http://search.default.svc.cluster.local/
        ports:
        - containerPort: 80
