apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: echo
    spec:
      containers:
      - name: echo
        image: tomwilkie/echo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
