apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qotd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: qotd
    spec:
      containers:
      - name: qotd
        image: tomwilkie/qotd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4446
