apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: search
    spec:
      containers:
      - name: search
        image: tomwilkie/searchapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        args:
          - -addr=:80
          - -target=http://elasticsearch.default.svc.cluster.local:9200

