#!/usr/bin/env bash
#
# Find all files with a given MIME type.
#
# e.g.
#     $ files-with-type text/x-shellscript k8s infra
#
# Assumes `find`, `xargs`, and `file` are all installed.

mime_type=$1
shift

find  "$@" -print0 -type f |xargs -0 file --mime-type | grep "${mime_type}" | sed -e 's/:.*$//'
