apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: weavescope-app
    namespace: kube-system
    labels:
      name: weavescope-app
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          provider: weavescope-app
      spec:
        containers:
        - name: weavescope-app
          image: weaveworks/scope:0.15
          args:
          - --no-probe
          - --app.weave.addr=
          ports:
          - containerPort: 4040
            hostPort: 4040
- apiVersion: v1
  kind: Service
  metadata:
    name: weavescope-app
    namespace: kube-system
  spec:
    type: LoadBalancer
    ports:
    - name: app
      port: 4040
    selector:
      name: weavescope-app
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: weavescope-probe
    namespace: kube-system
  spec:
    template:
      metadata:
        name:  weavescope-probe
      spec:
        hostPID: true
        hostNetwork: true
        containers:
        - name:  weavescope-probe
          image: weaveworks/scope:0.15
          args:
          - --no-app
          - --probe.docker=true
          - --probe.kubernetes=true
          - --probe.weave.addr=
          - --probe.docker.bridge=docker0
          - --probe.resolver=$(KUBE_DNS_SERVICE_HOST):$(KUBE_DNS_SERVICE_PORT)
          - weave-scope-app.kube-system.svc.cluster.local:4040
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 50m
          volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
        volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
