---

- name: docker pull images used by k8s tests
  docker_image:
    name: '{{ item }}'
    state: present
  with_items:
    - gcr.io/google_containers/etcd-amd64:{{ etcd_container_version }}
    - gcr.io/google_containers/kube-apiserver-amd64:v{{ kubernetes_version }}
    - gcr.io/google_containers/kube-controller-manager-amd64:v{{ kubernetes_version }}
    - gcr.io/google_containers/kube-proxy-amd64:v{{ kubernetes_version }}
    - gcr.io/google_containers/kube-scheduler-amd64:v{{ kubernetes_version }}
    - gcr.io/google_containers/kube-discovery-amd64:{{ kube_discovery_container_version }}
    - gcr.io/google_containers/pause-amd64:{{ pause_container_version }}
