FROM aarch64/alpine:3.5
MAINTAINER Weaveworks Inc <help@weave.works>
LABEL works.weave.role=system
WORKDIR /home/weave
RUN apk add --update bash conntrack-tools iproute2 util-linux curl && \
	rm -rf /var/cache/apk/*
ADD ./docker /usr/local/bin/
ADD ./weave ./weaveutil /usr/bin/
COPY ./scope /home/weave/
ENTRYPOINT ["/home/weave/scope", "--mode=probe", "--no-app", "--probe.docker=true"]
