---
# Install Docker's dependencies
# See also: https://docs.docker.com/engine/installation/linux/ubuntulinux/#install

- name: install linux-image-extra-*/virtual
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
