---
################################################################################
# Install Docker from Docker's official repository and Weave Net.
################################################################################

- name: install docker and weave net for development
  hosts: all
  gather_facts: false  # required in case Python is not available on the host
  become: true
  become_user: root

  pre_tasks:
    - include: library/setup_ansible_dependencies.yml

  roles:
    - setup-apt
    - dev-tools
    - golang-from-tarball
    - docker-install
    # Do not run this role when building with Vagrant, as sources have been already checked out:
    - { role: weave-net-sources, when: "ansible_user != 'vagrant'" }
