import _ from 'lodash';

const ACTION_TYPES = [
  'CHANGE_TOPOLOGY_OPTION',
  'CLEAR_CONTROL_ERROR',
  'CLICK_CLOSE_DETAILS',
  'CLICK_NODE',
  'CLICK_TOPOLOGY',
  'CLOSE_WEBSOCKET',
  'DO_CONTROL',
  'DO_CONTROL_ERROR',
  'DO_CONTROL_SUCCESS',
  'ENTER_EDGE',
  'ENTER_NODE',
  'HIT_ESC_KEY',
  'LEAVE_EDGE',
  'LEAVE_NODE',
  'OPEN_WEBSOCKET',
  'RECEIVE_NODE_DETAILS',
  'RECEIVE_NODES',
  'RECEIVE_NODES_DELTA',
  'RECEIVE_TOPOLOGIES',
  'RECEIVE_API_DETAILS',
  'RECEIVE_ERROR',
  'ROUTE_TOPOLOGY'
];

export default _.zipObject(ACTION_TYPES, ACTION_TYPES);
