/* Intervals in ms */
export const API_REFRESH_INTERVAL = 30000;
export const TOPOLOGY_REFRESH_INTERVAL = 5000;
export const NODES_DELTA_BUFFER_FEED_INTERVAL = 1000;

export const TOPOLOGY_LOADER_DELAY = 100;

export const TABLE_ROW_FOCUS_DEBOUNCE_INTERVAL = 10;
export const VIEWPORT_RESIZE_DEBOUNCE_INTERVAL = 200;
export const ZOOM_CACHE_DEBOUNCE_INTERVAL = 500;
export const TIMELINE_DEBOUNCE_INTERVAL = 500;

export const TIMELINE_TICK_INTERVAL = 100;
export const TIMELINE_SLIDER_UPDATE_INTERVAL = 10000;
